# Generated by Django 3.0.5 on 2020-04-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tariffs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="is_leaf",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
