# Generated by Django 3.0.5 on 2020-04-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tariffs", "0003_auto_20200420_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="is_leaf",
            field=models.BooleanField(default=False),
        ),
    ]
