# Generated by Django 3.0.5 on 2020-04-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tariffs", "0004_auto_20200420_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="duty",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="price",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="vat",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="volume",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
