# Generated by Django 3.0.5 on 2020-04-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0005_auto_20200420_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tariffs.Heading'),
        ),
    ]
